### ISSUE TITLE
Book Publish api

### ISSUE THREAD

**Issue by akshay98kv** [Tiya/BookNPenApp#6]
ReferenceError: jwt is not defined
    at verifyToken (/home/akshay/Desktop/bookread/BookNPenApp/backend/routes/addBookRoutes.js:112:19)
    at Layer.handle [as handle_request] (/home/akshay/Desktop/bookread/BookNPenApp/backend/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/akshay/Desktop/bookread/BookNPenApp/backend/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/akshay/Desktop/bookread/BookNPenApp/backend/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/akshay/Desktop/bookread/BookNPenApp/backend/node_modules/express/lib/router/layer.js:95:5)
    at /home/akshay/Desktop/bookread/BookNPenApp/backend/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/akshay/Desktop/bookread/BookNPenApp/backend/node_modules/express/lib/router/index.js:346:12)
    at next (/home/akshay/Desktop/bookread/BookNPenApp/backend/node_modules/express/lib/router/index.js:280:10)
    at jsonParser (/home/akshay/Desktop/bookread/BookNPenApp/backend/node_modules/body-parser/lib/types/json.js:119:7)
    at Layer.handle [as handle_request] (/home/akshay/Desktop/bookread/BookNPenApp/backend/node_modules/express/lib/router/layer.js:95:5)

**Comment by Abhilash-Raju** [comment]
Require the jwt token package into the module
var jwt = require('jsonwebtoken');
